// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/proto/FileMessage.proto
// Protobuf Java Version: 4.28.0

package com.signer.domain.proto;

public interface FileMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.signer.FileMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>map&lt;string, bytes&gt; attributes = 2;</code>
   */
  int getAttributesCount();
  /**
   * <code>map&lt;string, bytes&gt; attributes = 2;</code>
   */
  boolean containsAttributes(
      String key);
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @Deprecated
  java.util.Map<String, com.google.protobuf.ByteString>
  getAttributes();
  /**
   * <code>map&lt;string, bytes&gt; attributes = 2;</code>
   */
  java.util.Map<String, com.google.protobuf.ByteString>
  getAttributesMap();
  /**
   * <code>map&lt;string, bytes&gt; attributes = 2;</code>
   */
  /* nullable */
com.google.protobuf.ByteString getAttributesOrDefault(
      String key,
      /* nullable */
com.google.protobuf.ByteString defaultValue);
  /**
   * <code>map&lt;string, bytes&gt; attributes = 2;</code>
   */
  com.google.protobuf.ByteString getAttributesOrThrow(
      String key);
}
